# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild LangSoundTSF.sln /m /t:Build /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LangSoundTSF-${{ matrix.configuration }}-${{ matrix.platform }}
        path: |
          **\\${{ matrix.platform }}\\${{ matrix.configuration }}\\*.dll
          **\\${{ matrix.platform }}\\${{ matrix.configuration }}\\*.exe
  
